# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HN_Pra19_IOS_Movie_App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HN_Pra19_IOS_Movie_App
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'SDWebImage'
  pod 'ProgressHUD'
  pod "ToastViewSwift"

end
